Fueler-io/Web-Development-Resources

README.md
Added some free hosting platforms and also Added a new column for Helpful Chrome Extensions
=> Added Web hosting Platforms and some others

README.md
Hi. I have added a new icon website which is completely free.
=> Added a new free icon website

README.md
Added a few resources which helped me but were not present here
=> Added few resources

README.md
Added a new resource "colormind", which uses deep learning for generating colors.
=> docs: added new resource for css

README.md
Added resources for 3D.
-Includes both Free and Demo version resources.
=> Added 3D Illustrations

README.md
Added New Category named Coding Challenges
1. #100DaysOfCode
https://www.100daysofcode.com/
2. #JavaScript30
https://javascript30.com/
3. #100DaysCSS
https://100dayscss.com/
=> Added New Category named Coding Challenges

README.md
Hi! 
I added youtube channels, hosting, podcasts, remote job sites, icons, fonts etc. I've also refactored the readme file.
Please review.
Thank you.
=> added several resources

README.md
Added advanced JavaScript related resources which are free :)
=> Added  advanced JavaScript resources

README.md
Added YouTube Channels -
1. Clever Programmer
2. Sonny Sangha
3. The Coding Train
4. Codedamn
5. Dapp University
6. Adrian Twarog
7. Hitesh Choudhary
8. DesignCode
9. DesignCourse
Added Coding Platforms -
1. HackerEarth
2. Geeksforgeeks
=> Added YouTube Channels and Coding platforms

README.md
Added following resources,
1. Django Girls Tutorial
2. Cssbuttons.io
=> Add Django Girls Tutorial and Cssbuttons.io

README.md
Added Web dev libraries , code editor and learning platform resources
=> Added Web dev libraries resources

README.md
Youtube Channels:
Resource Icons:
=> added 5 more icon packs and 3 youtube channels

README.md
=> Added some helpful resources for Images and Illustrations

README.md
Closes issue #62 
This is under hacktoberfest. Kindly merge it.
=> Add YT Channel and Chrome Extension

README.md
Added CSS, JavaScript resources, and One coding challenge platform
=> Add: Resources added

README.md
Added a iconn resource that is "phosphor icon" and a youtube channel for web developers.
=> Added resources for icon and youtube channels

README.md
=> #57 issue resolved

README.md
=> I added CodeParade

README.md
Added YT channel : "CS50" and "programming with Mosh" in README.md
=> Updated a YT channel

README.md
Added best Github repos for JavaScript Questions and its clean code.
=> Updated the JAVAScript Section

README.md
@aquibj0 please check and let me know
=> Updated Chrome Extension Section Based on #70

README.md
Bonus Resources
* CSS Diner (Awesome way to learn and practice CSS Selectors)
Chrome Extensions
* VisBug
* ColorZilla
=> Add CSS Bonus Resources, Chrome Extensions

README.md
Replaced Heroku with AwardSpace
=> Removed Heroku from Free Hosting List
